---
- name: Créer le groupe node_exporter
  ansible.builtin.group:
    name: node_exporter
    system: true
    state: present

- name: Créer l'utilisateur système node_exporter
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Vérifier si Node Exporter est déjà installé
  ansible.builtin.stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_binary

- name: Télécharger Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
  when: not node_exporter_binary.stat.exists

- name: Extraire l'archive Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true
  when: not node_exporter_binary.stat.exists

- name: Copier le binaire dans /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: true
  when: not node_exporter_binary.stat.exists

- name: Déployer le service systemd Node Exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Recharger systemd et redémarrer Node Exporter

- name: S'assurer que Node Exporter est démarré et activé
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
